[GENERAL]
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
KEEP_ALIVE = "5m" # How long to keep Ollama models loaded into memory. (Instead of using -1 use "-1m")

[MODELS.OPENAI]
API_KEY = "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"

[MODELS.GROQ]
API_KEY = ""

[MODELS.ANTHROPIC]
API_KEY = ""

[MODELS.GEMINI]
API_KEY = ""

[MODELS.CUSTOM_OPENAI]
API_KEY = ""
API_URL = ""
MODEL_NAME = ""

[MODELS.OLLAMA]
API_URL = "" # Ollama API URL - http://host.docker.internal:11434

[MODELS.DEEPSEEK]
API_KEY = ""

[MODELS.AIMLAPI]
API_KEY = "" # Required to use AI/ML API chat and embedding models

[MODELS.LM_STUDIO]
API_URL = "" # LM Studio API URL - http://host.docker.internal:1234

[API_ENDPOINTS]
SEARXNG = "" # SearxNG API URL - http://localhost:32768
